name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Configure known hosts
        run: ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
      - name: SSH key
        run: ${{ secrets.SSH_KEY }} >> ~/.ssh/id_rsa
      - name: SSH command
        run: ssh  ${{ secrets.HOST }}
      - name: git clone
        run: git clone https://github.com/tlima84/mySpringBootInit.git