name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password 2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        port: 22
        key: ${{ secrets.SSH_KEY }}
        script: git clone https://github.com/tlima84/mySpringBootInit.git
